---
- name: The K8s Module
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
  - name: create a testing namespace
    k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present
  - name: Run an nginx deployment
    k8s:
      name: nginx
      src: nginx-deployment.yaml
  - name: Expose the nginx deployment
    k8s:
      name: nginx
      src: nginx-svc.yaml
  - name: Scale nginx deployment
    k8s_scale:
      api_version: v1
      kind: Deployment
      name: nginx
      namespace: testing
      replicas: 3
      wait_timeout: 60
