---
- name: The K8s Module
  hosts: localhost
  connection: local
  gather_facts: no
  tasks: 
  - name: Get a list of all pods
    k8s_info:
      api_version: v1
      kind: pod
      namespace: testing
    register: pod
  - name: Get a list of running pods
    k8s_info:
      api_version: v1
      kind: pod
      namespace: capi-system
      field_selectors:
        - status.phase=Running
    register: running_pods
  - name: debug
    debug:
      var: pod
      var: running_pods
